### ISSUE TITLE
Error when php-fpm is running on other instance 

### ISSUE THREAD

**Issue by jigneshthummar** [jderusse/composer-warmup#7]
on running command
`composer warmup-opcode `
i am getting following error
`Fatal error: Uncaught Error: Call to undefined function Jderusse\Warmup\Compiler\socket_create_listen() in /srv/.composer/vendor/jderusse/composer-warmup/src/Compiler/PhpServerCompiler.php:95 
Stack trace: 
#0 /srv/.composer/vendor/jderusse/composer-warmup/src/Compiler/PhpServerCompiler.php(83): Jderusse\Warmup\Compiler\PhpServerCompiler->isPortAvailable(8000) 
#1 /srv/.composer/vendor/jderusse/composer-warmup/src/Compiler/PhpServerCompiler.php(20): Jderusse\Warmup\Compiler\PhpServerCompiler->findPort(Array) 
#2 /srv/.composer/vendor/jderusse/composer-warmup/src/Console/WarmupCommand.php(62): Jderusse\Warmup\Compiler\PhpServerCompiler->__construct() 
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(242): Jderusse\Warmup\Console\WarmupCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#4 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(843): Symfony\Component\Console\Command\Command->run(Object(Symfony\Compo in /srv/.composer/vendor/jderusse/composer-warmup/src/Compiler/PhpServerCompiler.php on line 95 `

 The PhpServerCompiler.php file has following configured:

    public function __construct(array $portRange = [8000, 8999])

    {

        $port = $this->findPort($portRange);

        $this->address = sprintf('127.0.0.1:%d', $port);

        $this->startServer();

    }

Now, since php-fpm is not hosted on the same server, I am not sure how we can override that with real options. I've tried adding as "php-fpm" but it does not work.

**Comment by jderusse** [comment]
Try to install the extension `sockets`.

If it works can you please submit a PR to add the extension in the composer's requirements?

**Comment by nemke82** [comment]
@jderusse can you elaborate which extension sockets exactly?

**Comment by jderusse** [comment]
I'm talking about this extension http://php.net/manual/en/book.sockets.php.

You have to install it (depends on your Operating System) and enable it (adding `extension=sockets.so` in your .ini file)
